package GUI;

public class Contactos extends javax.swing.JFrame {

    public Contactos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        capaBackground = new javax.swing.JPanel();
        jb_retroceder = new javax.swing.JButton();
        bienvenida2 = new javax.swing.JLabel();
        blancoCurva = new MyContainers.PanelRound();
        panelRound3 = new MyContainers.PanelRound();
        As2 = new javax.swing.JLabel();
        n8 = new javax.swing.JLabel();
        panelRound4 = new MyContainers.PanelRound();
        As4 = new javax.swing.JLabel();
        n12 = new javax.swing.JLabel();
        panelRound6 = new MyContainers.PanelRound();
        As = new javax.swing.JLabel();
        PaSe = new javax.swing.JLabel();
        n6 = new javax.swing.JLabel();
        panelRound7 = new MyContainers.PanelRound();
        As3 = new javax.swing.JLabel();
        n13 = new javax.swing.JLabel();
        n9 = new javax.swing.JLabel();
        n14 = new javax.swing.JLabel();
        n15 = new javax.swing.JLabel();
        n16 = new javax.swing.JLabel();
        n17 = new javax.swing.JLabel();
        facebook1 = new javax.swing.JLabel();
        facebook2 = new javax.swing.JLabel();
        facebook3 = new javax.swing.JLabel();
        facebook4 = new javax.swing.JLabel();
        facebook5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        n18 = new javax.swing.JLabel();
        n19 = new javax.swing.JLabel();
        panelRound8 = new MyContainers.PanelRound();
        As6 = new javax.swing.JLabel();
        n22 = new javax.swing.JLabel();
        As9 = new javax.swing.JLabel();
        panelRound10 = new MyContainers.PanelRound();
        As8 = new javax.swing.JLabel();
        n23 = new javax.swing.JLabel();
        n24 = new javax.swing.JLabel();
        background1 = new MyContainers.Background();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        capaBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_retroceder.setBackground(new java.awt.Color(38, 65, 115));
        jb_retroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackIcon.png"))); // NOI18N
        jb_retroceder.setBorder(null);
        jb_retroceder.setContentAreaFilled(false);
        jb_retroceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_retroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_retrocederActionPerformed(evt);
            }
        });
        capaBackground.add(jb_retroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 20, -1, -1));

        bienvenida2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bienvenida2.setForeground(new java.awt.Color(255, 255, 255));
        bienvenida2.setText("CONTACTO");
        capaBackground.add(bienvenida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        blancoCurva.setBackground(new java.awt.Color(232, 235, 241));
        blancoCurva.setRoundTopLeft(80);
        blancoCurva.setRoundTopRight(80);
        blancoCurva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound3.setBackground(new java.awt.Color(204, 204, 204));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        As2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        As2.setForeground(new java.awt.Color(41, 61, 109));
        As2.setText("Soporte aula virtual");
        panelRound3.add(As2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 18, -1, -1));

        n8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n8.setForeground(new java.awt.Color(41, 61, 109));
        n8.setText("317-1010 opción 1");
        n8.setAlignmentX(0.5F);
        panelRound3.add(n8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 44, -1, -1));

        blancoCurva.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 192, 88));

        panelRound4.setBackground(new java.awt.Color(204, 204, 204));
        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setRoundTopLeft(20);
        panelRound4.setRoundTopRight(20);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        As4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        As4.setForeground(new java.awt.Color(41, 61, 109));
        As4.setText("Emergencias USIL");
        panelRound4.add(As4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 20, -1, -1));

        n12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n12.setForeground(new java.awt.Color(41, 61, 109));
        n12.setText("317-1090");
        n12.setAlignmentX(0.5F);
        panelRound4.add(n12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 45, -1, -1));

        blancoCurva.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 200, 88));

        panelRound6.setBackground(new java.awt.Color(204, 204, 204));
        panelRound6.setRoundBottomLeft(20);
        panelRound6.setRoundBottomRight(20);
        panelRound6.setRoundTopLeft(20);
        panelRound6.setRoundTopRight(20);
        panelRound6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        As.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        As.setForeground(new java.awt.Color(41, 61, 109));
        As.setText("Aseguradora");
        panelRound6.add(As, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 8, -1, -1));

        PaSe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PaSe.setForeground(new java.awt.Color(41, 61, 109));
        PaSe.setText("Pacifico Seguros");
        panelRound6.add(PaSe, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 32, -1, -1));

        n6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n6.setForeground(new java.awt.Color(41, 61, 109));
        n6.setText("415-1515");
        n6.setAlignmentX(0.5F);
        panelRound6.add(n6, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 58, -1, 12));

        blancoCurva.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 193, 88));

        panelRound7.setBackground(new java.awt.Color(204, 204, 204));
        panelRound7.setRoundBottomLeft(20);
        panelRound7.setRoundBottomRight(20);
        panelRound7.setRoundTopLeft(20);
        panelRound7.setRoundTopRight(20);
        panelRound7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        As3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        As3.setForeground(new java.awt.Color(41, 61, 109));
        As3.setText("Asesor de servicios");
        panelRound7.add(As3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, -1, -1));

        n13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n13.setForeground(new java.awt.Color(41, 61, 109));
        n13.setText("atencionalumno@usil.edu.pe");
        n13.setAlignmentX(0.5F);
        panelRound7.add(n13, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 55, -1, -1));

        n9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n9.setForeground(new java.awt.Color(41, 61, 109));
        n9.setText("317-1010 opción 3");
        n9.setAlignmentX(0.5F);
        panelRound7.add(n9, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 33, -1, -1));

        blancoCurva.add(panelRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 193, 88));

        n14.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        n14.setForeground(new java.awt.Color(41, 61, 109));
        n14.setText("www.facebook.com/usil.peru");
        n14.setAlignmentX(0.5F);
        blancoCurva.add(n14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 368, -1, -1));

        n15.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        n15.setForeground(new java.awt.Color(41, 61, 109));
        n15.setText("www.twitter.com/_USIL");
        n15.setAlignmentX(0.5F);
        blancoCurva.add(n15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 402, -1, -1));

        n16.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        n16.setForeground(new java.awt.Color(41, 61, 109));
        n16.setText("www.instagram.com/usil/");
        n16.setAlignmentX(0.5F);
        blancoCurva.add(n16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 436, -1, -1));

        n17.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        n17.setForeground(new java.awt.Color(41, 61, 109));
        n17.setText("www.youtube.com/user/usilpe");
        n17.setAlignmentX(0.5F);
        blancoCurva.add(n17, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 368, -1, -1));

        facebook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facebookRedi.png"))); // NOI18N
        facebook1.setText("jLabel2");
        blancoCurva.add(facebook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 363, 25, -1));

        facebook2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/instagramRedi2.png"))); // NOI18N
        facebook2.setText("jLabel2");
        blancoCurva.add(facebook2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 431, 25, 25));

        facebook3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/youtubeRedi.png"))); // NOI18N
        facebook3.setText("jLabel2");
        blancoCurva.add(facebook3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 363, 25, -1));

        facebook4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tiktokRedi2.png"))); // NOI18N
        facebook4.setText("jLabel2");
        blancoCurva.add(facebook4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 25, 25));

        facebook5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whatsappRedi2.png"))); // NOI18N
        facebook5.setText("jLabel2");
        blancoCurva.add(facebook5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 431, 25, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TwitterXRedi3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        blancoCurva.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 400, 28, -1));

        n18.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        n18.setForeground(new java.awt.Color(41, 61, 109));
        n18.setText("www.tiktok.com/@usil.edu");
        n18.setAlignmentX(0.5F);
        blancoCurva.add(n18, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 405, -1, -1));

        n19.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        n19.setForeground(new java.awt.Color(41, 61, 109));
        n19.setText("981-313-100");
        n19.setAlignmentX(0.5F);
        blancoCurva.add(n19, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 436, -1, -1));

        panelRound8.setBackground(new java.awt.Color(204, 204, 204));
        panelRound8.setRoundBottomLeft(20);
        panelRound8.setRoundBottomRight(20);
        panelRound8.setRoundTopLeft(20);
        panelRound8.setRoundTopRight(20);
        panelRound8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        As6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        As6.setForeground(new java.awt.Color(41, 61, 109));
        As6.setText("Central Telefónica USIL");
        panelRound8.add(As6, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 280, -1, -1));

        n22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n22.setForeground(new java.awt.Color(41, 61, 109));
        n22.setText("317-1000");
        n22.setAlignmentX(0.5F);
        panelRound8.add(n22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 45, -1, -1));

        As9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        As9.setForeground(new java.awt.Color(41, 61, 109));
        As9.setText("Central Telefónica USIL");
        panelRound8.add(As9, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 20, -1, -1));

        blancoCurva.add(panelRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 250, 200, 88));

        panelRound10.setBackground(new java.awt.Color(204, 204, 204));
        panelRound10.setRoundBottomLeft(20);
        panelRound10.setRoundBottomRight(20);
        panelRound10.setRoundTopLeft(20);
        panelRound10.setRoundTopRight(20);
        panelRound10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        As8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        As8.setForeground(new java.awt.Color(41, 61, 109));
        As8.setText("Soporte INFOSIL");
        panelRound10.add(As8, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 9, -1, -1));

        n23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n23.setForeground(new java.awt.Color(41, 61, 109));
        n23.setText("helpdesk@usil.edu.pe");
        n23.setAlignmentX(0.5F);
        panelRound10.add(n23, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 55, -1, -1));

        n24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        n24.setForeground(new java.awt.Color(41, 61, 109));
        n24.setText("317-1010 opción 2");
        n24.setAlignmentX(0.5F);
        panelRound10.add(n24, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 33, -1, -1));

        blancoCurva.add(panelRound10, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 140, 200, 88));

        capaBackground.add(blancoCurva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 440, 490));

        background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        capaBackground.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capaBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capaBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_retrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_retrocederActionPerformed
        // TODO add your handling code here:
        Inicio ventanaInicio = new Inicio();
        ventanaInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_retrocederActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel As;
    private javax.swing.JLabel As2;
    private javax.swing.JLabel As3;
    private javax.swing.JLabel As4;
    private javax.swing.JLabel As6;
    private javax.swing.JLabel As8;
    private javax.swing.JLabel As9;
    private javax.swing.JLabel PaSe;
    private MyContainers.Background background1;
    private javax.swing.JLabel bienvenida2;
    private MyContainers.PanelRound blancoCurva;
    private javax.swing.JPanel capaBackground;
    private javax.swing.JLabel facebook1;
    private javax.swing.JLabel facebook2;
    private javax.swing.JLabel facebook3;
    private javax.swing.JLabel facebook4;
    private javax.swing.JLabel facebook5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jb_retroceder;
    private javax.swing.JLabel n12;
    private javax.swing.JLabel n13;
    private javax.swing.JLabel n14;
    private javax.swing.JLabel n15;
    private javax.swing.JLabel n16;
    private javax.swing.JLabel n17;
    private javax.swing.JLabel n18;
    private javax.swing.JLabel n19;
    private javax.swing.JLabel n22;
    private javax.swing.JLabel n23;
    private javax.swing.JLabel n24;
    private javax.swing.JLabel n6;
    private javax.swing.JLabel n8;
    private javax.swing.JLabel n9;
    private MyContainers.PanelRound panelRound10;
    private MyContainers.PanelRound panelRound3;
    private MyContainers.PanelRound panelRound4;
    private MyContainers.PanelRound panelRound6;
    private MyContainers.PanelRound panelRound7;
    private MyContainers.PanelRound panelRound8;
    // End of variables declaration//GEN-END:variables
}
