package GUI;

import Funcionamiento.ListaUsuarios;
import Funcionamiento.Usuario;
import MyContainers.TextPrompt;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;


public class Login extends JFrame {
     
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        setBackground(new Color(0, 0,0, 0));
        
        this.aviso.setVisible(false);
        this.fondoAviso.setVisible(false);
        this.labelNota.setVisible(false);
        this.labelMayus.setVisible(false);
        this.labelUsuario.setVisible(false);
        this.salirAviso.setVisible(false);
        
        TextPrompt txtCorreo = new TextPrompt("Username", txtEmail);
        TextPrompt txtContra = new TextPrompt("Password", jp_password_recovery);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ultimaCapa = new javax.swing.JPanel();
        salirAviso = new javax.swing.JButton();
        labelMayus = new javax.swing.JLabel();
        labelNota = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        aviso = new javax.swing.JLabel();
        fondoAviso = new javax.swing.JLabel();
        botonVerContraseña = new javax.swing.JButton();
        jb_salir = new javax.swing.JButton();
        botonLogin = new MyContainers.BotonCustomLogin();
        personaGUI = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        candadoGUI = new javax.swing.JLabel();
        jp_password_recovery = new javax.swing.JPasswordField();
        botonLoginVisitante = new javax.swing.JButton();
        botonOlvidaContra = new javax.swing.JButton();
        logoUsil = new javax.swing.JLabel();
        fondoLogin = new javax.swing.JLabel();
        fondoCurveadoDegradado1 = new MyContainers.FondoCurveadoDegradado();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        ultimaCapa.setBackground(new java.awt.Color(102, 102, 102));
        ultimaCapa.setOpaque(false);
        ultimaCapa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salirAviso.setBackground(new java.awt.Color(42, 57, 115));
        salirAviso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconoSalir35x35.png"))); // NOI18N
        salirAviso.setBorder(null);
        salirAviso.setBorderPainted(false);
        salirAviso.setContentAreaFilled(false);
        salirAviso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirAviso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirAvisoActionPerformed(evt);
            }
        });
        ultimaCapa.add(salirAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 232, -1, -1));

        labelMayus.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelMayus.setForeground(new java.awt.Color(255, 255, 255));
        labelMayus.setText("con exactitud (Mayus/Minus).");
        ultimaCapa.add(labelMayus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 348, -1, -1));

        labelNota.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelNota.setForeground(new java.awt.Color(255, 255, 255));
        labelNota.setText("Nota: Asegurarse de digitar su clave ");
        ultimaCapa.add(labelNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 330, 220, -1));

        labelUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelUsuario.setText("Usuario y/o Contraseña no válido. ");
        ultimaCapa.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 295, 210, -1));

        aviso.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        aviso.setForeground(new java.awt.Color(255, 255, 255));
        aviso.setText("AVISO");
        ultimaCapa.add(aviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 245, -1, -1));

        fondoAviso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoAviso.png"))); // NOI18N
        ultimaCapa.add(fondoAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 280, 210));

        botonVerContraseña.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        botonVerContraseña.setForeground(new java.awt.Color(255, 255, 255));
        botonVerContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ojoblancoraya25x18.png"))); // NOI18N
        botonVerContraseña.setBorder(null);
        botonVerContraseña.setBorderPainted(false);
        botonVerContraseña.setContentAreaFilled(false);
        botonVerContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVerContraseña.setFocusPainted(false);
        botonVerContraseña.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botonVerContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerContraseñaActionPerformed(evt);
            }
        });
        ultimaCapa.add(botonVerContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 307, -1, -1));

        jb_salir.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jb_salir.setForeground(new java.awt.Color(255, 255, 255));
        jb_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconoSalir35x35.png"))); // NOI18N
        jb_salir.setBorder(null);
        jb_salir.setBorderPainted(false);
        jb_salir.setContentAreaFilled(false);
        jb_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_salir.setFocusPainted(false);
        jb_salir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jb_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirActionPerformed(evt);
            }
        });
        ultimaCapa.add(jb_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 20, 30, -1));

        botonLogin.setText("LOG IN");
        botonLogin.setBorderPainted(false);
        botonLogin.setFocusPainted(false);
        botonLogin.setFont(new java.awt.Font("Franklin Gothic Book", 1, 16)); // NOI18N
        botonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLoginActionPerformed(evt);
            }
        });
        ultimaCapa.add(botonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 410, 250, 50));

        personaGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoMuñueco.png"))); // NOI18N
        ultimaCapa.add(personaGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 240, -1, -1));

        txtEmail.setBackground(new java.awt.Color(63, 108, 165));
        txtEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setToolTipText("");
        txtEmail.setBorder(null);
        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        ultimaCapa.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 230, 160, 50));
        txtEmail.getAccessibleContext().setAccessibleName("");

        candadoGUI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        candadoGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoCandado.png"))); // NOI18N
        candadoGUI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ultimaCapa.add(candadoGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 300, -1, -1));

        jp_password_recovery.setBackground(new java.awt.Color(63, 108, 165));
        jp_password_recovery.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jp_password_recovery.setForeground(new java.awt.Color(255, 255, 255));
        jp_password_recovery.setBorder(null);
        jp_password_recovery.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jp_password_recovery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jp_password_recoveryActionPerformed(evt);
            }
        });
        ultimaCapa.add(jp_password_recovery, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 290, 160, 50));

        botonLoginVisitante.setBackground(new java.awt.Color(63, 108, 165));
        botonLoginVisitante.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        botonLoginVisitante.setForeground(new java.awt.Color(255, 255, 255));
        botonLoginVisitante.setText("Log in as a visitor");
        botonLoginVisitante.setBorder(null);
        botonLoginVisitante.setBorderPainted(false);
        botonLoginVisitante.setContentAreaFilled(false);
        botonLoginVisitante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLoginVisitante.setFocusPainted(false);
        botonLoginVisitante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonLoginVisitante.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonLoginVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLoginVisitanteActionPerformed(evt);
            }
        });
        ultimaCapa.add(botonLoginVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 365, 100, -1));

        botonOlvidaContra.setBackground(new java.awt.Color(63, 108, 165));
        botonOlvidaContra.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        botonOlvidaContra.setForeground(new java.awt.Color(255, 255, 255));
        botonOlvidaContra.setText("Forgot ¿Password?");
        botonOlvidaContra.setBorder(null);
        botonOlvidaContra.setBorderPainted(false);
        botonOlvidaContra.setContentAreaFilled(false);
        botonOlvidaContra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonOlvidaContra.setFocusPainted(false);
        botonOlvidaContra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botonOlvidaContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOlvidaContraActionPerformed(evt);
            }
        });
        ultimaCapa.add(botonOlvidaContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 365, 100, -1));

        logoUsil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usilLogo150x150.png"))); // NOI18N
        ultimaCapa.add(logoUsil, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 85, 140, 130));

        fondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoLogin.png"))); // NOI18N
        ultimaCapa.add(fondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 150, -1, 360));

        fondoCurveadoDegradado1.setRoundBottomLeft(50);
        fondoCurveadoDegradado1.setRoundBottomRight(50);
        fondoCurveadoDegradado1.setRoundTopLeft(50);
        fondoCurveadoDegradado1.setRoundTopRight(50);

        javax.swing.GroupLayout fondoCurveadoDegradado1Layout = new javax.swing.GroupLayout(fondoCurveadoDegradado1);
        fondoCurveadoDegradado1.setLayout(fondoCurveadoDegradado1Layout);
        fondoCurveadoDegradado1Layout.setHorizontalGroup(
            fondoCurveadoDegradado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        fondoCurveadoDegradado1Layout.setVerticalGroup(
            fondoCurveadoDegradado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        ultimaCapa.add(fondoCurveadoDegradado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ultimaCapa, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ultimaCapa, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jp_password_recoveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jp_password_recoveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jp_password_recoveryActionPerformed
   
    private void botonOlvidaContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOlvidaContraActionPerformed
        RecuperarClave rClave = new RecuperarClave();
        rClave.setVisible(true);
        this.setVisible(false);  
    }//GEN-LAST:event_botonOlvidaContraActionPerformed

    private void botonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLoginActionPerformed
        // TODO add your handling code here:
        String username = txtEmail.getText();
        String contrasena = new String(jp_password_recovery.getPassword());
        
        ListaUsuarios l_us = new ListaUsuarios();
        
        for(Usuario us : l_us.getUsuarios()){
            if(us.getNombreUsuario().equals(username) && us.getContrasenha().equals(contrasena)){
                Inicio ventanaInicio = new Inicio(us);
                ventanaInicio.setVisible(true);
                this.setVisible(false);     
            } else {
                //Si el correo no esta registrado o esta mal
                this.aviso.setVisible(true);
                this.fondoAviso.setVisible(true);
                this.labelMayus.setVisible(true);
                this.labelUsuario.setVisible(true);
                this.labelNota.setVisible(true);
                this.salirAviso.setVisible(true);
                this.jb_salir.setVisible(false);
                this.botonVerContraseña.setVisible(false);
                this.personaGUI.setVisible(false);
                this.txtEmail.setVisible(false);
                this.candadoGUI.setVisible(false);
                this.jp_password_recovery.setVisible(false);
                this.botonOlvidaContra.setVisible(false);      
            }
        }
    }//GEN-LAST:event_botonLoginActionPerformed

    private void jb_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jb_salirActionPerformed

    private void botonVerContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerContraseñaActionPerformed
        ImageIcon nuevaImagen;
        if (jp_password_recovery.getEchoChar() == '\u2022') {
            jp_password_recovery.setEchoChar((char) 0);
            nuevaImagen = new ImageIcon(getClass().getResource("/images/ojoblanco25x14.png"));
        } else {
            jp_password_recovery.setEchoChar('\u2022');
            nuevaImagen = new ImageIcon(getClass().getResource("/images/ojoblancoraya25x18.png"));
        }

        botonVerContraseña.setIcon(nuevaImagen);
    }//GEN-LAST:event_botonVerContraseñaActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void salirAvisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirAvisoActionPerformed
        // TODO add your handling code here:
        Login ventanaLogin = new Login();
        ventanaLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_salirAvisoActionPerformed

    private void botonLoginVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLoginVisitanteActionPerformed
        Inicio ventanaInicio = new Inicio();
        ventanaInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonLoginVisitanteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aviso;
    private MyContainers.BotonCustomLogin botonLogin;
    private javax.swing.JButton botonLoginVisitante;
    private javax.swing.JButton botonOlvidaContra;
    private javax.swing.JButton botonVerContraseña;
    private javax.swing.JLabel candadoGUI;
    private javax.swing.JLabel fondoAviso;
    private MyContainers.FondoCurveadoDegradado fondoCurveadoDegradado1;
    private javax.swing.JLabel fondoLogin;
    private javax.swing.JButton jb_salir;
    private javax.swing.JPasswordField jp_password_recovery;
    private javax.swing.JLabel labelMayus;
    private javax.swing.JLabel labelNota;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel logoUsil;
    private javax.swing.JLabel personaGUI;
    private javax.swing.JButton salirAviso;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPanel ultimaCapa;
    // End of variables declaration//GEN-END:variables
}
