package GUI;

import Funcionamiento.Estudiante;
import java.awt.Color;
import javax.swing.JFrame;

public class PagoAviso extends JFrame {
    private Estudiante estudiante;
    private SaldosYPagos ventanaSaldosYPagos;
    private MetodoDePago ventanaMetodoDePago;
    
    public PagoAviso(Estudiante es, SaldosYPagos saldosYPagos) { //Confirmado
        initComponents();
        this.estudiante = es;
        this.ventanaSaldosYPagos = saldosYPagos;
        this.setLocationRelativeTo(null);
        setBackground(new Color(0, 0,0, 0));
        
        jl_check_icon_error.setVisible(false);
        jl_textoFondo1.setVisible(false);
        jl_textoFondo2.setVisible(false);
        botonVolver.setVisible(false);
    }
    
    public PagoAviso(Estudiante es, MetodoDePago metodoDePago) { // Error
        initComponents();
        this.estudiante = es;
        this.ventanaMetodoDePago = metodoDePago;
        this.setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));

        jl_check_icon_check.setVisible(false);
        botonHecho.setVisible(false);
        jl_textoFondo.setVisible(false);
        jl_texto_check1.setVisible(false);
        jl_resultadoPago.setText("Transacción Fallida");

        jl_texto_comprobado.setText("Los datos ingresados son incorrectos");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UltimaCapa = new javax.swing.JPanel();
        jl_textoFondo = new javax.swing.JLabel();
        panelBlancoCurva = new MyContainers.PanelRound();
        jl_resultadoPago = new javax.swing.JLabel();
        jl_texto_check1 = new javax.swing.JLabel();
        jl_texto_comprobado = new javax.swing.JLabel();
        jl_check_icon_check = new javax.swing.JLabel();
        jl_check_icon_error = new javax.swing.JLabel();
        botonHecho = new MyContainers.BotonCustomLogin();
        botonVolver = new MyContainers.BotonCustomLogin();
        logoUsil = new javax.swing.JLabel();
        jl_textoFondo1 = new javax.swing.JLabel();
        jl_textoFondo2 = new javax.swing.JLabel();
        fondoCurveadoDegradado1 = new MyContainers.FondoCurveadoDegradado();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        UltimaCapa.setMinimumSize(new java.awt.Dimension(490, 490));
        UltimaCapa.setOpaque(false);
        UltimaCapa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_textoFondo.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jl_textoFondo.setForeground(new java.awt.Color(255, 255, 255));
        jl_textoFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_textoFondo.setText("Gracias!");
        UltimaCapa.add(jl_textoFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 140, -1));

        panelBlancoCurva.setBackground(new java.awt.Color(232, 235, 241));
        panelBlancoCurva.setRoundBottomLeft(50);
        panelBlancoCurva.setRoundBottomRight(50);
        panelBlancoCurva.setRoundTopLeft(80);
        panelBlancoCurva.setRoundTopRight(80);
        panelBlancoCurva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_resultadoPago.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jl_resultadoPago.setForeground(new java.awt.Color(41, 61, 109));
        jl_resultadoPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_resultadoPago.setText("Pago Exitoso!");
        jl_resultadoPago.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jl_resultadoPago.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jl_resultadoPago.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelBlancoCurva.add(jl_resultadoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 120, 392, -1));

        jl_texto_check1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jl_texto_check1.setForeground(new java.awt.Color(41, 61, 109));
        jl_texto_check1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_texto_check1.setText("Se le enviará la boleta a su correo"); // NOI18N
        jl_texto_check1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jl_texto_check1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jl_texto_check1.setInheritsPopupMenu(false);
        jl_texto_check1.setVerifyInputWhenFocusTarget(false);
        panelBlancoCurva.add(jl_texto_check1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 175, 260, 20));
        jl_texto_check1.getAccessibleContext().setAccessibleDescription("");

        jl_texto_comprobado.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jl_texto_comprobado.setForeground(new java.awt.Color(41, 61, 109));
        jl_texto_comprobado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_texto_comprobado.setText("Su pago se ha completado correctamente"); // NOI18N
        jl_texto_comprobado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jl_texto_comprobado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jl_texto_comprobado.setInheritsPopupMenu(false);
        jl_texto_comprobado.setVerifyInputWhenFocusTarget(false);
        panelBlancoCurva.add(jl_texto_comprobado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 155, 320, 20));

        jl_check_icon_check.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CheckIcon.png"))); // NOI18N
        panelBlancoCurva.add(jl_check_icon_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 40, -1, -1));

        jl_check_icon_error.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EquisIcon.png"))); // NOI18N
        panelBlancoCurva.add(jl_check_icon_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 40, -1, -1));

        botonHecho.setText("Hecho");
        botonHecho.setFocusable(false);
        botonHecho.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonHecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHechoActionPerformed(evt);
            }
        });
        panelBlancoCurva.add(botonHecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 100, 50));

        botonVolver.setText("Volver");
        botonVolver.setFocusable(false);
        botonVolver.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        panelBlancoCurva.add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 100, 50));

        UltimaCapa.add(panelBlancoCurva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 440, 284));

        logoUsil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usilLogo150x150.png"))); // NOI18N
        UltimaCapa.add(logoUsil, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 60, 140, 130));

        jl_textoFondo1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jl_textoFondo1.setForeground(new java.awt.Color(255, 255, 255));
        jl_textoFondo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_textoFondo1.setText("Hubo un error con los datos");
        UltimaCapa.add(jl_textoFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 440, -1));

        jl_textoFondo2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jl_textoFondo2.setForeground(new java.awt.Color(255, 255, 255));
        jl_textoFondo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_textoFondo2.setText("ingresados");
        UltimaCapa.add(jl_textoFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 440, -1));

        fondoCurveadoDegradado1.setRoundTopLeft(50);
        fondoCurveadoDegradado1.setRoundTopRight(50);
        fondoCurveadoDegradado1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        UltimaCapa.add(fondoCurveadoDegradado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UltimaCapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UltimaCapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonHechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHechoActionPerformed
        ventanaSaldosYPagos.estadoCuotaFaltante(false);
        ventanaSaldosYPagos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonHechoActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        ventanaMetodoDePago.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UltimaCapa;
    private MyContainers.BotonCustomLogin botonHecho;
    private MyContainers.BotonCustomLogin botonVolver;
    private MyContainers.FondoCurveadoDegradado fondoCurveadoDegradado1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jl_check_icon_check;
    private javax.swing.JLabel jl_check_icon_error;
    private javax.swing.JLabel jl_resultadoPago;
    private javax.swing.JLabel jl_textoFondo;
    private javax.swing.JLabel jl_textoFondo1;
    private javax.swing.JLabel jl_textoFondo2;
    private javax.swing.JLabel jl_texto_check1;
    private javax.swing.JLabel jl_texto_comprobado;
    private javax.swing.JLabel logoUsil;
    private MyContainers.PanelRound panelBlancoCurva;
    // End of variables declaration//GEN-END:variables
}
