package GUI;

import Funcionamiento.Usuario;
import java.awt.Color;
import javax.swing.JFrame;

public class TransaccionFallida extends JFrame {
    private Usuario usuario;
    private MetodoDePago ventanaMetodoDePago;
    
    public TransaccionFallida(Usuario us, MetodoDePago metodoDePago) {
        initComponents();
        this.usuario = us;
        this.ventanaMetodoDePago = metodoDePago;
        this.setLocationRelativeTo(null);
        setBackground(new Color(0, 0,0, 0));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UltimaCapa = new javax.swing.JPanel();
        jl_textoFondo1 = new javax.swing.JLabel();
        jl_textoFondo2 = new javax.swing.JLabel();
        panelBlancoCurva = new MyContainers.PanelRound();
        jl_resultadoPago = new javax.swing.JLabel();
        jl_texto1 = new javax.swing.JLabel();
        jl_check_icon = new javax.swing.JLabel();
        botonVolver = new MyContainers.BotonCustomLogin();
        logoUsil = new javax.swing.JLabel();
        fondoCurveadoDegradado1 = new MyContainers.FondoCurveadoDegradado();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        UltimaCapa.setMinimumSize(new java.awt.Dimension(490, 490));
        UltimaCapa.setOpaque(false);
        UltimaCapa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_textoFondo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jl_textoFondo1.setForeground(new java.awt.Color(255, 255, 255));
        jl_textoFondo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_textoFondo1.setText("Hubo un error con los datos");
        UltimaCapa.add(jl_textoFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jl_textoFondo2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jl_textoFondo2.setForeground(new java.awt.Color(255, 255, 255));
        jl_textoFondo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_textoFondo2.setText("ingresados");
        UltimaCapa.add(jl_textoFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        panelBlancoCurva.setBackground(new java.awt.Color(232, 235, 241));
        panelBlancoCurva.setRoundBottomLeft(50);
        panelBlancoCurva.setRoundBottomRight(50);
        panelBlancoCurva.setRoundTopLeft(80);
        panelBlancoCurva.setRoundTopRight(80);
        panelBlancoCurva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_resultadoPago.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jl_resultadoPago.setForeground(new java.awt.Color(41, 61, 109));
        jl_resultadoPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_resultadoPago.setText("Transacción Fallida");
        jl_resultadoPago.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jl_resultadoPago.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jl_resultadoPago.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelBlancoCurva.add(jl_resultadoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 112, 392, -1));

        jl_texto1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_texto1.setForeground(new java.awt.Color(41, 61, 109));
        jl_texto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_texto1.setText("Los datos ingresados son incorrectos"); // NOI18N
        jl_texto1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jl_texto1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jl_texto1.setInheritsPopupMenu(false);
        jl_texto1.setVerifyInputWhenFocusTarget(false);
        panelBlancoCurva.add(jl_texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 144, 260, 20));

        jl_check_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EquisIcon.png"))); // NOI18N
        panelBlancoCurva.add(jl_check_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        botonVolver.setText("Volver");
        botonVolver.setFocusable(false);
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        panelBlancoCurva.add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 200, -1, -1));

        UltimaCapa.add(panelBlancoCurva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 440, 284));

        logoUsil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usilLogo150x150.png"))); // NOI18N
        UltimaCapa.add(logoUsil, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 60, 140, 130));

        fondoCurveadoDegradado1.setRoundTopLeft(50);
        fondoCurveadoDegradado1.setRoundTopRight(50);

        javax.swing.GroupLayout fondoCurveadoDegradado1Layout = new javax.swing.GroupLayout(fondoCurveadoDegradado1);
        fondoCurveadoDegradado1.setLayout(fondoCurveadoDegradado1Layout);
        fondoCurveadoDegradado1Layout.setHorizontalGroup(
            fondoCurveadoDegradado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        fondoCurveadoDegradado1Layout.setVerticalGroup(
            fondoCurveadoDegradado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        UltimaCapa.add(fondoCurveadoDegradado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UltimaCapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UltimaCapa, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        ventanaMetodoDePago.setUsuario(usuario);
        ventanaMetodoDePago.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UltimaCapa;
    private MyContainers.BotonCustomLogin botonVolver;
    private MyContainers.FondoCurveadoDegradado fondoCurveadoDegradado1;
    private javax.swing.JLabel jl_check_icon;
    private javax.swing.JLabel jl_resultadoPago;
    private javax.swing.JLabel jl_texto1;
    private javax.swing.JLabel jl_textoFondo1;
    private javax.swing.JLabel jl_textoFondo2;
    private javax.swing.JLabel logoUsil;
    private MyContainers.PanelRound panelBlancoCurva;
    // End of variables declaration//GEN-END:variables
}
